#!/bin/bash

GAMEDATADIR="GameData/TURD"
MHSourceFiles="TU_MH_AllInOne"
BGSourceFiles="TU_BG_AllInOne"

ZIPCMD=zip
ZIPOPTS="-r"

BASEARCHIVE=TURD
MHARCH=MH
BGARCH=BG
ALLARCH=MH-BG

RELEASE=prealpha
VERSION=002


$ZIPCMD $ZIPOPTS ${BASEARCHIVE}_${ALLARCH}_${RELEASE}_${VERSION} ${GAMEDATADIR}
$ZIPCMD $ZIPOPTS ${BASEARCHIVE}_${MHARCH}_${RELEASE}_${VERSION} ${GAMEDATADIR}/${MHSourceFiles}
$ZIPCMD $ZIPOPTS ${BASEARCHIVE}_${BGARCH}_${RELEASE}_${VERSION} ${GAMEDATADIR}/${BGSourceFiles}